version: '3.8'

services:

  mongodb:
    image: mongo:7
    container_name: market-impact-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: market-impact-ai
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: